name: develop-action
on:
  pull_request:
    types:
      - closed
    branches:    
      - 'develop'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repository
    - run: |
        echo README.md
 
